# Generated by Django 2.2.7 on 2019-11-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='asunto',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consulta',
            name='correo',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consulta',
            name='correo2',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consulta',
            name='mensaje',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='consulta',
            name='rut',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consulta',
            name='telefono',
            field=models.IntegerField(default=True),
        ),
    ]
