# Generated by Django 2.2.7 on 2019-11-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191120_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='correo2',
        ),
        migrations.AddField(
            model_name='consulta',
            name='confirmarcorreo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='asunto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='correo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='mensaje',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='rut',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
